### ISSUE TITLE
[FAQ] More details about `recommendation of Pod resource specifications (CPU, memory, etc.) intelligent algorithms`

### ISSUE THREAD

**Issue by niconical** [traas-stack/kapacity#31]
Thank you very much for open-sourcing Kapacity. Sharing experiences from the industry is very important for this field. My main research direction includes container workload resource recommendation, so even if the resource recommendation algorithm of Kapacity will be open-sourced in the future, I still want to learn about your ideas as soon as possible. Could you please provide a detailed introduction of the models and methods you use for resource recommendation?

Ref: https://kapacity.netlify.app/docs/roadmap/

**Comment by dayko2019** [comment]
Resource recommendation is still in experimentation in production and is a future plan of the project. Our initial idea is to optimize the k8s autoscaler's recommendation algorithm (based on moving window), and other advanced algorithms are still being explored. So currently we are not able to provide practical information about this.
