### ISSUE TITLE
in which time. the release version cloud get

### ISSUE THREAD

**Issue by jujiale** [traas-stack/kapacity#42]
### What would you like to be added?

according the wechat article  ([point this](https://mp.weixin.qq.com/s/JGC8P3T_uQKAaYOyPhdFiw)).  It says in June. the v0.2 will be publish. but I find it not get. what I more concerned is , in which time. I could get release version in order to use it in prod env.
  wait for your reply. thanks.

### Why is this needed?

want to know release version in which time could get

**Comment by zqzten** [comment]
Currently, v0.2 is estimated to be released at about late July ~ early August. Detailed process is tracked in this [milestone](https://github.com/traas-stack/kapacity/milestone/2).
