### ISSUE TITLE
as a user, if I can use http api control kapacity

### ISSUE THREAD

**Issue by jujiale** [traas-stack/kapacity#50]
### What would you like to be added?

Hello，I want to know, if I can use api（such as http invoke）,to control the kapacity behavior . If it is yes, where could I get the api?

### Why is this needed?

when I could use http method to control kapacity behavior， I could make our own control portal page. and use http api to publish config into k8s cluster.

**Comment by zqzten** [comment]
Kapacity use [CRDs](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) to extend Kubernetes API, so you can use [standard Kubernetes API](https://kubernetes.io/docs/concepts/overview/kubernetes-api/) to interact with Kapacity. The API definitions can be found [here](https://github.com/traas-stack/kapacity/tree/main/apis/autoscaling/v1alpha1).

**Comment by jujiale** [comment]
> Kapacity use [CRDs](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) to extend Kubernetes API, so you can use [standard Kubernetes API](https://kubernetes.io/docs/concepts/overview/kubernetes-api/) to interact with Kapacity. The API definitions can be found [here](https://github.com/traas-stack/kapacity/tree/main/apis).

thanks a lot
