### ISSUE TITLE
Can you provide the dataset required for algorithm training?

### ISSUE THREAD

**Issue by conghuhu** [traas-stack/kapacity#81]
### What would you like to be added?

The dataset required for algorithm training

### Why is this needed?

This can help our participants conduct algorithmic research and verify the excellence of the Kapacity algorithm

**Comment by zqzten** [comment]
For time-series forecating, we've previously open sourced a dataset, you can check it here: https://github.com/traas-stack/forecasting

**Comment by conghuhu** [comment]
@zqzten Thank you for providing the dataset.
But for replica count prediction, it seems that this dataset is not applicable

**Comment by zqzten** [comment]
That's right. Since there're no counterparts to the replicas estimation algorithm, currently we do not have a "standard" dataset for that. It's suggested that you could use the data from your real env to test its effect.
