### ISSUE TITLE
fetch_resource_metric_history failed

### ISSUE THREAD

**Issue by zhy76** [traas-stack/kapacity#91]
### What happened?

![image](https://github.com/traas-stack/kapacity/assets/56665618/b18180c7-9517-453e-80a9-f0bd6d9aa61c)
I followed the tutorial to create a ihpa : https://kapacity.netlify.app/zh-cn/docs/getting-started/quick-start/ihpa/predictive-scaling/#%E5%88%9B%E5%BB%BA%E9%85%8D%E7%BD%AE%E4%BA%86%E5%8A%A8%E6%80%81%E9%A2%84%E6%B5%8B%E5%BC%8F%E7%94%BB%E5%83%8F%E6%BA%90%E7%9A%84-ihpa, and I failed.

### What did you expect to happen?

success to run the job

### How can we reproduce it (as minimally and precisely as possible)?

https://kapacity.netlify.app/zh-cn/docs/getting-started/quick-start/ihpa/predictive-scaling/#%E5%88%9B%E5%BB%BA%E9%85%8D%E7%BD%AE%E4%BA%86%E5%8A%A8%E6%80%81%E9%A2%84%E6%B5%8B%E5%BC%8F%E7%94%BB%E5%83%8F%E6%BA%90%E7%9A%84-ihpa

### Kapacity version

<details>

</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

**Comment by zqzten** [comment]
dup of #90
